# Use an official Go runtime as a parent image
FROM golang:1.17-alpine

# Set the working directory to your app directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Expose port 8080 to the outside world
EXPOSE 8080

# Command to run the Go application
#CMD ["go", "run", "."]
